%YAML:1.0
sVideoPath: "rtsp://192.41.170.200:554/now.mp4"
codec: 0
iImgWidth: 1920
iImgHeight: 1080
fFPS: 30.
iCaptureMode: 0
iImageType: 1
bFileSizeGt2GB: 0
sCameraType: ipcam
iCameraNo: 1
iNumFramesToGrab: -1
iNumFramesToIgnore: 0
bSkipFrozenFrames: 1
bIsSetProxy: 0
sProxy: ""
bResizeImage: 0
iResizedImgHeight: -1
bWriteTimestampOnFrame: 1
bSaveVideo: 0
bSaveResizedVideo: 0
bForceEnableStream: 0
bIsSetThreadPriority: 0
iPriorityValue: 50
bEnableSnapshotBuf: 0
iNumFramesInSnapshotBuf: 20
iSnapshotBufFPS: 2
debugMode: 0
bGrabForever: 1
sHeartbeatFile: /home/marikhu/VGL_IQEYE
